name: Auto Dataset Pipeline

on:
  schedule:
    - cron: "0 * * * *"  # Ejecuta cada hora automáticamente
  workflow_dispatch:      # Permite ejecutar manualmente

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Generate synthetic dataset
        run: python Generador.py
        env:
          ROWS_PER_DATASET: 5000
          OUT_DIR: ./datasets
          PREFIX: dataset

      - name: Upload datasets to Pinata
        run: python CargadorDePiñata.py
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          UPLOADED_LOG: ./uploaded.log

      - name: Record real sale
        run: |
          # Aquí tu script de administrador de ingresos sin simulación
          python AdministradorDeIngresos.py record --amount 100.0 --currency USD --source market
        env:
          LEDGER_FILE: ./ledger.json

      - name: Show ledger (optional)
        run: python AdministradorDeIngresos.py show
        env:
          LEDGER_FILE: ./ledger.json
