name: Auto Dataset Pipeline (Premium $2,000)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  premium_dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo files & python version
        run: |
          echo "PWD: $(pwd)"
          echo "Repo top:"
          ls -la
          python -V || true
          find . -maxdepth 3 -type f -iname "*.py" -print || true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ALL dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests huggingface-hub
          echo "✅ All dependencies installed"

      - name: Generate premium dataset ($2,000)
        run: |
          mkdir -p ./datasets
          cd ./datasets
          python -u ../generator.py 2>&1 | tee ../gen.log
          echo "💰 Premium dataset generated - Price: $2,000 USD"
          ls -la

      - name: Upload to Hugging Face ($2,000)
        if: env.HF_TOKEN != ''
        run: |
          python upload_to_huggingface.py 2>&1 | tee hf_upload.log
          echo "🏆 Dataset listed at $2,000 USD on Hugging Face"
        env:
          HUGGINGFACE_HUB_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Upload to Pinata (Backup)
        if: env.PINATA_API_KEY != '' && env.PINATA_API_SECRET != ''
        working-directory: ./datasets
        run: |
          echo "Starting Pinata upload..."
          python -u ../uploader_pinata.py 2>&1 | tee ../upload.log
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          UPLOADED_LOG: ../uploaded.log

      - name: Check secrets status
        run: |
          echo "HF_TOKEN present: $([[ -n \"${{ secrets.HF_TOKEN }}\" ]] && echo '✅ YES' || echo '❌ NO')"
          echo "PINATA_API_KEY present: $([[ -n \"${{ secrets.PINATA_API_KEY }}\" ]] && echo '✅ YES' || echo '❌ NO')"
          echo "PINATA_API_SECRET present: $([[ -n \"${{ secrets.PINATA_API_SECRET }}\" ]] && echo '✅ YES' || echo '❌ NO')"

      - name: Upload all logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: premium-dataset-logs
          path: |
            gen.log
            hf_upload.log
            upload.log
            uploaded.log
