name: Auto Dataset Pipeline

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Quick diagnostic (files & python)
        run: |
          echo ">>> pwd: $(pwd)"
          ls -la
          find . -maxdepth 2 -type f -iname "*.py" -print || true
          python -V

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate synthetic dataset
        run: python generador.py
        env:
          ROWS_PER_DATASET: 5000
          OUT_DIR: ./datasets
          PREFIX: dataset

      - name: List generated files (debug)
        run: |
          echo ">>> ls datasets:"
          ls -la ./datasets || true
          echo ">>> head of any .meta.json:"
          head -n 20 ./datasets/*.meta.json || true

      - name: Upload datasets as artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: generated-datasets
          path: ./datasets

      - name: Upload datasets to Pinata
        if: ${{ secrets.PINATA_API_KEY && secrets.PINATA_API_SECRET }}
        working-directory: ./datasets
        run: python ../cargador_pinata.py
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          UPLOADED_LOG: ../uploaded.log

      - name: Skip upload warning (no secrets)
        if: ${{ !secrets.PINATA_API_KEY || !secrets.PINATA_API_SECRET }}
        run: echo "Pinata secrets not set; skipping upload step."

      - name: Record real sale
        run: python administrador_de_ingresos.py record --amount 100.0 --currency USD --source market
        env:
          LEDGER_FILE: ./ledger.json

      - name: Show ledger (optional)
        run: python administrador_de_ingresos.py show
        env:
          LEDGER_FILE: ./ledger.json
        continue-on-error: true
