name: Auto Dataset Pipeline (debug)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  debug_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo files & python version
        run: |
          echo "PWD: $(pwd)"
          echo "Repo top:"
          ls -la
          python -V || true
          find . -maxdepth 3 -type f -iname "*.py" -print || true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate dataset (verbose)
        run: |
          mkdir -p ./datasets
          python -u generador.py 2>&1 | tee gen.log
          ls -la ./datasets || true
          head -n 40 ./datasets/*.meta.json || true

      - name: Upload datasets+logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-datasets-and-logs
          path: |
            ./datasets
            gen.log

      - name: Check secrets presence
        run: |
          echo "PINATA_API_KEY present: $([[ -n \"${{ secrets.PINATA_API_KEY }}\" ]] && echo yes || echo no)"
          echo "PINATA_API_SECRET present: $([[ -n \"${{ secrets.PINATA_API_SECRET }}\" ]] && echo yes || echo no)"
        shell: bash

      - name: Upload datasets to Pinata (runs from datasets)
        if: ${{ secrets.PINATA_API_KEY != '' && secrets.PINATA_API_SECRET != '' }}
        working-directory: ./datasets
        run: |
          echo "PWD: $(pwd)"
          ls -la
          python -u ../cargador_pinata.py 2>&1 | tee ../upload.log
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          UPLOADED_LOG: ../uploaded.log

      - name: Upload upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: upload-logs
          path: |
            upload.log
            uploaded.log
